# Generated by Django 5.2 on 2025-05-02 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='datetime',
        ),
        migrations.AddField(
            model_name='reserve',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserve',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
